---
title: "1_Descriptive"
author: "Haotian Tan"
date: "2025-10-8"
output: html_document
---

```{r}
library(dplyr)

library(ggplot2)
library(ggExtra)
library(cowplot)

# setting theme of text for all figure (units pt)

custom_theme <-   theme_cowplot()+
theme(
    plot.title = element_text(size = 18), 
    axis.title = element_text(size = 16),  
    axis.text = element_text(size = 16),  
    legend.text = element_text(size = 16)  
)

```

```{r}
data_persona <- read.csv("merged_all_models_persona.csv", stringsAsFactors = FALSE) %>%
  mutate(condition = "persona")

data_nopersona <- read.csv("merged_all_models_nopersona.csv", stringsAsFactors = FALSE) %>%
  mutate(condition = "nopersona")

data <- bind_rows(data_persona, data_nopersona) %>%
  mutate(group = factor(group,
                        levels = c("Human", "GPT-3.5", "o3-mini", "DeepSeek-V3", "DeepSeek-R1")),
         condition = factor(condition, levels = c("persona", "nopersona")))

table(data$condition, data$group)
```

```{r}
data_list <- data %>%
  mutate(choice_label = factor(ifelse(choice == 1, "punish", "accept"),
                               levels = c("punish", "accept"))) %>%
  group_split(condition, group)
```

subplot of supplementary figure 6.1.3
```{r fig.width=3, fig.height=3, out.width="60%", fig.align="center", dpi=300}

plot_list_AA <- lapply(seq_along(data_list), function(i) {
  df <- data_list[[i]]
  group_name <- unique(df$group)
  condition <- unique(df$condition)
  plot_label <- letters[i]  

  p <- ggplot(df, aes(x = AA_valence, y = AA_arousal, color = choice_label)) +
    geom_point(alpha = 0.3) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
    scale_x_continuous(limits = c(-100, 100)) +
    scale_y_continuous(limits = c(-100, 100)) +
    coord_fixed(ratio = 1, clip = "off") +
    labs(
      title = plot_label,      
      subtitle = ifelse(group_name == "Human", 
                        "Human", 
                        paste(group_name, condition, sep = ", ")),
      x = "Emotion valence after allocation",
      y = "Emotion arousal after allocation"
    ) +
    custom_theme +
    theme(
      panel.border = element_rect(color = "black", fill = NA),
      legend.position = "none",
      plot.title = element_text(hjust = 0, size = 20, face = "bold"),      
      plot.subtitle = element_text(hjust = 0.5, size = 18, face = "bold") 
    )

  ggMarginal(p, type = "boxplot", groupColour = TRUE, groupFill = TRUE, size = 6)
})

for (i in seq_along(plot_list_AA)) {
  assign(paste0("fig_aae_choice", i), plot_list_AA[[i]])
}

```


```{r}
fig_aae_choice_gpt <- cowplot::plot_grid(fig_aae_choice2,fig_aae_choice6,ncol = 1)
fig_aae_choice_o3 <- cowplot::plot_grid(fig_aae_choice3,fig_aae_choice7,ncol = 1)
fig_aae_choice_v3 <- cowplot::plot_grid(fig_aae_choice4,fig_aae_choice8,ncol = 1)
fig_aae_choice_r1 <- cowplot::plot_grid(fig_aae_choice5,fig_aae_choice9,ncol = 1)

fig_aae_choice_llm <- cowplot::plot_grid(fig_aae_choice_gpt,fig_aae_choice_o3,
                                     fig_aae_choice_v3,fig_aae_choice_r1,
                                     ncol = 4)
ggsave(filename = "fig_aae_choice_llm.svg", plot = fig_aae_choice_llm, width = 24, height = 12)

```

```{r}
ggsave(filename = "fig_aae_choice_human.svg", plot = fig_aae_choice1, width = 6, height = 6)

```

subplot of supplementary figure 6.1.4
```{r fig.width=3, fig.height=3, out.width="60%", fig.align="center", dpi=300}

plot_list_AC <- lapply(seq_along(data_list), function(i) {
  df <- data_list[[i]]
  group_name <- unique(df$group)
  condition <- unique(df$condition)
  plot_label <- letters[i]  

  p <- ggplot(df, aes(x = AC_valence, y = AC_arousal, color = choice_label)) +
    geom_point(alpha = 0.3) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
    scale_x_continuous(limits = c(-100, 100)) +
    scale_y_continuous(limits = c(-100, 100)) +
    coord_fixed(ratio = 1, clip = "off") +
    labs(
      title = plot_label,      
      subtitle = ifelse(group_name == "Human", 
                        "Human", 
                        paste(group_name, condition, sep = ", ")),
      x = "Emotion valence after decision",
      y = "Emotion arousal after decision"
    ) +
    custom_theme +
    theme(
      panel.border = element_rect(color = "black", fill = NA),
      legend.position = "none",
      plot.title = element_text(hjust = 0, size = 20, face = "bold"),      
      plot.subtitle = element_text(hjust = 0.5, size = 18, face = "bold") 
    )

  ggMarginal(p, type = "boxplot", groupColour = TRUE, groupFill = TRUE, size = 6)
})

for (i in seq_along(plot_list_AC)) {
  assign(paste0("fig_ace_choice", i), plot_list_AC[[i]])
}

```

```{r}
fig_ace_choice_gpt <- cowplot::plot_grid(fig_ace_choice2,fig_ace_choice6,ncol = 1)
fig_ace_choice_o3 <- cowplot::plot_grid(fig_ace_choice3,fig_ace_choice7,ncol = 1)
fig_ace_choice_v3 <- cowplot::plot_grid(fig_ace_choice4,fig_ace_choice8,ncol = 1)
fig_ace_choice_r1 <- cowplot::plot_grid(fig_ace_choice5,fig_ace_choice9,ncol = 1)

fig_ace_choice_llm <- cowplot::plot_grid(fig_ace_choice_gpt,fig_ace_choice_o3,
                                     fig_ace_choice_v3,fig_ace_choice_r1,
                                     ncol = 4)
ggsave(filename = "fig_ace_choice_llm.svg", plot = fig_ace_choice_llm, width = 24, height = 12)

```


```{r}
ggsave(filename = "fig_ace_choice_human.svg", plot = fig_ace_choice1, width = 6, height = 6)

```



